#!/usr/bin/env node
// tools/build-icons.mjs
// 1. Scans markup/JS for Font Awesome usage, resolves each icon against
//    node_modules/@fortawesome/fontawesome-free/svgs/<style>/<name>.svg,
//    and (re)generates the §4 block in src/site.css as mask-image rules
//    re-using the SAME class names (fa-solid fa-x etc.) => zero markup changes.
// 2. Copies the official feather-icons UMD build to src/feather-local.js.
import fs from 'node:fs';
import path from 'node:path';

const SCAN = [
  'index.html','whitename.html','design.html','design-lab.html','Themes/Themes.html',
  'word/index.html','search/index.html','search/astra.js','AI/chat.html','AI/index.html','AI/manage.html',
  'AI/editor.html','AI/research.html','AI/tos.html','AI/privacy.html','AI/goals.html',
  'AI/version.html','AI/updatenotes.js','src/nav.js',
  ...fs.readdirSync('AI/js').filter(f => f.endsWith('.js')).map(f => 'AI/js/' + f),
].filter(p => fs.existsSync(p));

const STYLE_RE = /^fa-(solid|regular|brands)$/;
const UTILITY = new Set(['xs','sm','lg','xl','fw','spin','pulse','inverse','beat','fade','bounce','flip','shake',
  'flip-horizontal','flip-vertical','rotate-90','rotate-180','rotate-270','1x','2x','3x','4x','5x']);
const pairs = new Map(); // icon name -> style

for (const f of SCAN) {
  const txt = fs.readFileSync(f, 'utf8');
  for (const m of txt.matchAll(/class\s*=\s*"([^"]*)"|class\s*=\s*'([^']*)'/g)) {
    const tokens = (m[1] || m[2]).split(/\s+/).filter(Boolean);
    const style = (tokens.find(t => STYLE_RE.test(t)) || 'solid').replace('fa-', '');
    for (const t of tokens) {
      const mm = /^fa-([a-z0-9-]+)$/.exec(t);
      if (!mm || STYLE_RE.test(t) || UTILITY.has(mm[1])) continue;
      if (pairs.has(mm[1]) && pairs.get(mm[1]) !== style)
        console.warn(`WARN style conflict fa-${mm[1]}: ${pairs.get(mm[1])} vs ${style} (first wins)`);
      else pairs.set(mm[1], style);
    }
  }
  // safety net: fa-name appearing outside class attributes (rare JS building)
  for (const m of txt.matchAll(/\bfa-([a-z0-9-]+)\b/g)) {
    const n = m[1];
    if (!pairs.has(n) && !UTILITY.has(n) && !['solid','regular','brands'].includes(n)) {
      pairs.set(n, 'solid');
      console.warn(`WARN unpaired fa-${n} in ${f} — defaulting to solid`);
    }
  }
}

const FA_DIR = 'node_modules/@fortawesome/fontawesome-free/svgs';
const rules = [], missing = [];
for (const [name, style] of [...pairs].sort()) {
  let svg = null;
  for (const st of [style, 'solid', 'regular', 'brands']) {
    const p = `${FA_DIR}/${st}/${name}.svg`;
    if (fs.existsSync(p)) { svg = fs.readFileSync(p, 'utf8'); break; }
  }
  if (!svg) { missing.push(name); continue; }
  const uri = 'data:image/svg+xml,' + encodeURIComponent(svg.replace('<svg', '<svg fill="black"'));
  rules.push(`.fa-${name} {\n  display: inline-block; width: 1em; height: 1em; vertical-align: -0.125em;\n  background: currentColor;\n  -webkit-mask: url("${uri}") center / contain no-repeat;\n          mask: url("${uri}") center / contain no-repeat;\n}`);
}
if (missing.length) { console.error('MISSING ICONS: ' + missing.join(', ')); process.exit(1); }

const block = `/* ${rules.length} Font Awesome mask icons (from @fortawesome/fontawesome-free) */\n`
  + rules.join('\n\n')
  + `\n\n/* FA utilities actually used on the site */\n.fa-spin { animation: fa-spin 2s infinite linear; }\n@keyframes fa-spin { to { transform: rotate(360deg); } }\n`;

const SITE = 'src/site.css';
const css = fs.readFileSync(SITE, 'utf8');
const BEGIN = '/* §4 ICONS — generated by tools/build-icons.mjs: begin */';
const END = '/* §4 ICONS — generated: end */';
if (!css.includes(BEGIN) || !css.includes(END)) { console.error('§4 markers missing in src/site.css'); process.exit(1); }
// NOTE: BEGIN/END contain regex-special chars (/* */ .) — they must be escaped
// before going into `new RegExp`, otherwise the pattern never matches and the
// replace below is a silent no-op.
const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
fs.writeFileSync(SITE, css.replace(new RegExp(esc(BEGIN) + '[\\s\\S]*?' + esc(END)), BEGIN + '\n' + block + END));

fs.copyFileSync('node_modules/feather-icons/dist/feather.min.js', 'src/feather-local.js');
console.log(`§4: ${rules.length} icons written; src/feather-local.js written (${(fs.statSync('src/feather-local.js').size/1024).toFixed(0)}kb)`);
